# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 14:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('focusgroups', '0004_focusgroup_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=450)),
                ('archivo', models.FileField(upload_to='documentos/')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Cientificos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=450)),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='cientificos/')),
                ('slug', models.SlugField(editable=False, max_length=450)),
                ('cargo', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=200)),
                ('perfil', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Country')),
            ],
            options={
                'verbose_name': 'Cient\xedfico',
                'verbose_name_plural': 'Cient\xedficos',
            },
        ),
        migrations.CreateModel(
            name='Organizaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=450)),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='organizaciones/')),
                ('direccion', models.CharField(blank=True, max_length=450, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(editable=False, max_length=450)),
                ('url', models.URLField(blank=True, null=True)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Country')),
            ],
            options={
                'verbose_name': 'Organizaci\xf3n',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=450)),
                ('slug', models.SlugField(editable=False, max_length=450)),
                ('fecha', models.DateField()),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='imagenes/')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.AddField(
            model_name='archivos',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacion.Proyectos'),
        ),
    ]
