# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name': 'Proyecto/Publicaci\xf3n', 'verbose_name_plural': 'Proyectos/Publicaciones'},
        ),
    ]
