# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 19:09
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0003_listacorreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='imagen_principal',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(upload_to='imagenes/', verbose_name='Imagen detalle'),
        ),
    ]
