# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0004_auto_20170301_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='idioma',
            field=models.IntegerField(choices=[(1, 'Espa\xf1ol'), (2, 'Ingles'), (3, 'Espa\xf1ol/Ingles')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='imagen_principal',
            field=sorl.thumbnail.fields.ImageField(upload_to='imagenes/', verbose_name='Imagen portada'),
        ),
    ]
