# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalconfigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgroup',
            name='es_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
