# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalconfigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=450)),
                ('common_name', models.CharField(blank=True, max_length=450, null=True)),
                ('cultivar', models.IntegerField(blank=True, choices=[(1, 'Animal'), (2, 'Plant')], null=True)),
                ('type_species', models.IntegerField(blank=True, choices=[(1, 'Annual'), (2, 'Perrenial')], null=True)),
                ('food_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalconfigs.FoodGroup')),
                ('name_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalconfigs.NameFamily')),
                ('name_genus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalconfigs.NameGenus')),
                ('name_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalconfigs.NameOrder')),
                ('name_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalconfigs.NameSpecies')),
            ],
            options={
                'ordering': ['scientific_name'],
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together=set([('scientific_name', 'common_name')]),
        ),
    ]
