# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='name_genus',
        ),
        migrations.RemoveField(
            model_name='species',
            name='name_species',
        ),
        migrations.AddField(
            model_name='species',
            name='name_genus1',
            field=models.CharField(default=2, max_length=100, verbose_name='Name genus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='name_species1',
            field=models.CharField(default=1, max_length=100, verbose_name='Name species'),
            preserve_default=False,
        ),
    ]
