# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='fct_source_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='fct_source_descr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='optifood_group',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='optifood_sub_group',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='ret_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='ret_descr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='vol_wt_calc_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='vol_wt_calc_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='vol_wt_descr_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='vol_wt_source',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='vol_wt_source_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='alcar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='ash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='b1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='b12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='b2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='b3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='b6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='becar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='becry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='ca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='carbohidrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='cooking_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='species.CookingMethod'),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='dfe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='dry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='fe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='fe_heme',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='fe_non_heme',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='fol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='folac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='iron_animal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='lodine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='na',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='phy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='pnto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='retinol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='va_rae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='va_re',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='vit_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='zn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
