# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FctEspecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_method', models.IntegerField(choices=[(1, 'Raw'), (2, 'Not consumed'), (3, 'Fresh'), (4, 'Dried')])),
                ('dry', models.FloatField()),
                ('water', models.FloatField()),
                ('energy', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('ash', models.FloatField()),
                ('carbohidrate', models.FloatField()),
                ('ca', models.FloatField()),
                ('fe', models.FloatField()),
                ('mg', models.FloatField()),
                ('na', models.FloatField()),
                ('zn', models.FloatField()),
                ('vit_c', models.FloatField()),
                ('b1', models.FloatField()),
                ('b2', models.FloatField()),
                ('b3', models.FloatField()),
                ('pnto', models.FloatField()),
                ('b6', models.FloatField()),
                ('dfe', models.FloatField()),
                ('fol', models.FloatField()),
                ('folac', models.FloatField()),
                ('b12', models.FloatField()),
                ('va_re', models.FloatField()),
                ('va_rae', models.FloatField()),
                ('retinol', models.FloatField()),
                ('alcar', models.FloatField()),
                ('becar', models.FloatField()),
                ('becry', models.FloatField()),
                ('phy', models.FloatField()),
                ('lodine', models.FloatField()),
                ('fe_heme', models.FloatField()),
                ('fe_non_heme', models.FloatField()),
                ('iron_animal', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='scientific_name2',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='species_english_name',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='species_french_name',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='species_vernacular_name',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.Species'),
        ),
    ]
