# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_auto_20160905_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='fctespecies',
            name='sci_name',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
