# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_fctespecies_vol_wt_descr_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', sorl.thumbnail.fields.ImageField(upload_to='species/')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.Species')),
            ],
        ),
    ]
