# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_fotosspecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='cultivar2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='cultivar',
            field=models.IntegerField(blank=True, choices=[(1, 'Animal'), (2, 'Plant')], null=True, verbose_name='Kingdom'),
        ),
    ]
