# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_auto_20170105_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='fctespecies',
            name='formula',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='sum_proximates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='fct_source_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='fct_source_descr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='vol_wt_source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='cultivar',
            field=models.IntegerField(blank=True, choices=[(1, 'Animal'), (2, 'Plant'), (3, 'Fungi'), (4, 'Chromista')], null=True, verbose_name='Kingdom'),
        ),
    ]
