# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0007_auto_20170111_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fctespecies',
            name='alcar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='fctespecies',
            name='cooking_method',
        ),
        migrations.AddField(
            model_name='fctespecies',
            name='cooking_method',
            field=models.ManyToManyField(blank=True, to='species.CookingMethod'),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='va_rae',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='vit_c',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fctespecies',
            name='vol_wt_descr_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
