# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_auto_20170112_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fctespecies',
            name='becar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
