# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_auto_20170112_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fctespecies',
            name='phy',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
