# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='location',
            name='community',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='province',
        ),
        migrations.RemoveField(
            model_name='community',
            name='province',
        ),
        migrations.RemoveField(
            model_name='focusgroup',
            name='location',
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.IntegerField(choices=[(1, 'APAC'), (2, 'SSA'), (3, 'Mena'), (4, 'LatAm')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Community'),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Country'),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Province'),
        ),
        migrations.AlterField(
            model_name='community',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Country'),
        ),
        migrations.AlterField(
            model_name='province',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Province'),
        ),
        migrations.AddField(
            model_name='community',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.County'),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.County'),
        ),
    ]
