# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0002_auto_20160808_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusgroup',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Both')], default=1),
            preserve_default=False,
        ),
    ]
