# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0002_auto_20160905_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusgroup',
            name='climate',
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='annual_mean_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='climate_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Climate'),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
