# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0003_focusgroup_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusgroup',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='crp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.CRP'),
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='definition_seasons',
            field=models.IntegerField(blank=True, choices=[(1, 'Year-Round (Y)'), (2, 'Lean Season (L)')], null=True),
        ),
        migrations.RemoveField(
            model_name='focusgroup',
            name='ethnic_group',
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='ethnic_group',
            field=models.ManyToManyField(blank=True, to='focusgroups.EthnicGroup'),
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='frecuency',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Female'), (2, 'Male'), (3, 'Both')], null=True),
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='hh',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='focusgroup',
            name='language',
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='language',
            field=models.ManyToManyField(blank=True, to='focusgroups.Language'),
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='method_observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Organizations'),
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='scientist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusgroups.Scientists'),
        ),
    ]
