# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0003_auto_20161021_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusgroup',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
