# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 14:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0005_auto_20161202_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', sorl.thumbnail.fields.ImageField(upload_to='focus_groups/')),
                ('focus_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focusgroups.FocusGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='scientists',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scientists',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='scientists',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='cientificos/'),
        ),
        migrations.AlterField(
            model_name='scientists',
            name='perfil',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scientists',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
