# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0005_remove_ethnicgroup_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusgroup',
            name='gender',
        ),
    ]
