# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0006_auto_20161212_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusgroup',
            name='market_distance',
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='ameant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='market',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='market_distance_1',
            field=models.FloatField(blank=True, help_text='in km', null=True),
        ),
    ]
