# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0006_remove_focusgroup_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusgroup',
            name='method_observations',
        ),
        migrations.RemoveField(
            model_name='scientists',
            name='country',
        ),
        migrations.RemoveField(
            model_name='scientists',
            name='gender',
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='climate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Female'), (2, 'Male'), (3, 'Both')], null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='lean_season',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='market_distance',
            field=models.TextField(blank=True, help_text='in km', null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='population',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='year_round',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.IntegerField(choices=[(1, 'APAC'), (2, 'LatAm'), (3, 'South Asia'), (4, 'Asia'), (5, 'Africa')]),
        ),
    ]
