# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0007_auto_20170109_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusgroup',
            name='method_observations',
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='market',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
