# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0007_auto_20160817_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusgroup',
            name='definition_seasons',
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='method_observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
