# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0008_auto_20160817_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusgroup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
