# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0008_auto_20170111_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusgroup',
            name='market',
            field=models.TextField(blank=True, null=True),
        ),
    ]
