# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0009_auto_20160817_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcacode',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='fcacode',
            name='parts_used',
        ),
        migrations.AddField(
            model_name='fcacode',
            name='parts_used',
            field=models.ManyToManyField(blank=True, to='focusgroups.PartUsed'),
        ),
        migrations.AlterField(
            model_name='fcacode',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='species.Species'),
        ),
        migrations.RemoveField(
            model_name='fcacode',
            name='uses',
        ),
        migrations.AddField(
            model_name='fcacode',
            name='uses',
            field=models.ManyToManyField(blank=True, to='focusgroups.Uses'),
        ),
    ]
