# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0010_auto_20160819_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcacode',
            name='uses',
        ),
        migrations.AddField(
            model_name='fcacode',
            name='uses',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
