# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusgroups', '0010_country_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='email_persona_contacto',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='puesto_persona_contacto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
